In [5]:
import pickle

enron_data = pickle.load(open("../final_project/final_project_dataset.pkl", "rb"))
print("here")
print(len(enron_data))

here
146

In [6]:
import pandas as pd

df=pd.DataFrame.from_dict(enron_data)
df=df.T
df

,bonus,deferral_payments,deferred_income,director_fees,email_address,exercised_stock_options,expenses,from_messages,from_poi_to_this_person,from_this_person_to_poi,...,long_term_incentive,other,poi,restricted_stock,restricted_stock_deferred,salary,shared_receipt_with_poi,to_messages,total_payments,total_stock_value
METTS MARK,600000,NaN,NaN,NaN,mark.metts@enron.com,NaN,94299,29,38,1,...,NaN,1740,False,585062,NaN,365788,702,807,1061827,585062
BAXTER JOHN C,1200000,1295738,-1386055,NaN,NaN,6680544,11200,NaN,NaN,NaN,...,1586055,2660303,False,3942714,NaN,267102,NaN,NaN,5634343,10623258
ELLIOTT STEVEN,350000,NaN,-400729,NaN,steven.elliott@enron.com,4890344,78552,NaN,NaN,NaN,...,NaN,12961,False,1788391,NaN,170941,NaN,NaN,211725,6678735
CORDES WILLIAM R,NaN,NaN,NaN,NaN,bill.cordes@enron.com,651850,NaN,12,10,0,...,NaN,NaN,False,386335,NaN,NaN,58,764,NaN,1038185
HANNON KEVIN P,1500000,NaN,-3117011,NaN,kevin.hannon@enron.com,5538001,34039,32,32,21,...,1617011,11350,True,853064,NaN,243293,1035,1045,288682,6391065
MORDAUNT KRISTINA M,325000,NaN,NaN,NaN,kristina.mordaunt@enron.com,NaN,35018,NaN,NaN,NaN,...,NaN,1411,False,208510,NaN,267093,NaN,NaN,628522,208510
MEYER ROCKFORD G,NaN,1848227,NaN,NaN,rockford.meyer@enron.com,493489,NaN,28,0,0,...,NaN,NaN,False,462384,NaN,NaN,22,232,1848227,955873
MCMAHON JEFFREY,2600000,NaN,NaN,NaN,jeffrey.mcmahon@enron.com,1104054,137108,48,58,26,...,694862,297353,False,558801,NaN,370448,2228,2355,4099771,1662855
HAEDICKE MARK E,1150000,2157527,-934484,NaN,mark.haedicke@enron.com,608750,76169,1941,180,61,...,983346,52382,False,524169,-329825,374125,1847,4009,3859065,803094
PIPER GREGORY F,400000,1130036,-33333,NaN,greg.piper@enron.com,880290,43057,222,61,48,...,NaN,778,False,409554,-409554,197091,742,1238,1737629,880290
HUMPHREY GENE E,NaN,2964506,NaN,NaN,gene.humphrey@enron.com,2282768,4994,17,10,17,...,NaN,NaN,False,NaN,NaN,130724,119,128,3100224,2282768
NOLES JAMES L,NaN,774401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,False,463261,-94556,NaN,NaN,NaN,774401,368705
BLACHMAN JEREMY M,850000,NaN,NaN,NaN,jeremy.blachman@enron.com,765313,84208,14,25,2,...,831809,272,False,189041,NaN,248546,2326,2475,2014835,954354
SUNDE MARTIN,700000,NaN,NaN,NaN,marty.sunde@enron.com,NaN,NaN,38,37,13,...,476451,111122,False,698920,NaN,257486,2565,2647,1545059,698920
GIBBS DANA R,NaN,504610,NaN,NaN,dana.gibbs@enron.com,2218275,NaN,12,0,0,...,461912,NaN,False,NaN,NaN,NaN,23,169,966522,2218275
LOWRY CHARLES P,NaN,NaN,NaN,NaN,NaN,372205,NaN,NaN,NaN,NaN,...,NaN,NaN,False,153686,-153686,NaN,NaN,NaN,NaN,372205
COLWELL WESLEY,1200000,27610,-144062,NaN,wes.colwell@enron.com,NaN,16514,40,240,11,...,NaN,101740,True,698242,NaN,288542,1132,1758,1490344,698242
MULLER MARK S,1100000,842924,-719000,NaN,s..muller@enron.com,1056320,NaN,16,12,0,...,1725545,947,False,360528,NaN,251654,114,136,3202070,1416848
JACKSON CHARLENE R,250000,NaN,NaN,NaN,charlene.jackson@enron.com,185063,10181,56,25,19,...,NaN,2435,False,540672,NaN,288558,117,258,551174,725735
WESTFAHL RICHARD K,NaN,NaN,-10800,NaN,dick.westfahl@enron.com,NaN,51870,NaN,NaN,NaN,...,256191,401130,False,384930,NaN,63744,NaN,NaN,762135,384930
WALTERS GARETH W,NaN,53625,NaN,NaN,NaN,1030329,33785,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,87410,1030329
WALLS JR ROBERT H,850000,NaN,NaN,NaN,rob.walls@enron.com,4346544,50936,146,17,0,...,540751,2,False,1552453,NaN,357091,215,671,1798780,5898997
KITCHEN LOUISE,3100000,NaN,NaN,NaN,louise.kitchen@enron.com,81042,5774,1728,251,194,...,NaN,93925,False,466101,NaN,271442,3669,8305,3471141,547143
CHAN RONNIE,NaN,NaN,-98784,98784,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,False,32460,-32460,NaN,NaN,NaN,NaN,NaN
BELFER ROBERT,NaN,-102500,NaN,3285,NaN,3285,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,44093,NaN,NaN,NaN,102500,-44093
SHANKMAN JEFFREY A,2000000,NaN,NaN,NaN,jeffrey.shankman@enron.com,1441898,178979,2681,94,83,...,554422,1191,False,630137,NaN,304110,1730,3221,3038702,2072035
WODRASKA JOHN,NaN,NaN,NaN,NaN,john.wodraska@enron.com,NaN,NaN,NaN,NaN,NaN,...,NaN,189583,False,NaN,NaN,NaN,NaN,NaN,189583,NaN
BERGSIEKER RICHARD P,250000,NaN,-485813,NaN,rick.bergsieker@enron.com,NaN,59175,59,4,0,...,180250,427316,False,659249,NaN,187922,233,383,618850,659249
URQUHART JOHN A,NaN,NaN,-36666,36666,NaN,NaN,228656,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,228656,NaN
BIBI PHILIPPE A,1000000,NaN,NaN,NaN,philippe.bibi@enron.com,1465734,38559,40,23,8,...,369721,425688,False,378082,NaN,213625,1336,1607,2047593,1843816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
PICKERING MARK R,300000,NaN,NaN,NaN,mark.pickering@enron.com,28798,31653,67,7,0,...,NaN,NaN,False,NaN,NaN,655037,728,898,1386690,28798
BHATNAGAR SANJAY,NaN,NaN,NaN,137864,sanjay.bhatnagar@enron.com,2604490,NaN,29,0,1,...,NaN,137864,False,-2604490,15456290,NaN,463,523,15456290,NaN
CARTER REBECCA C,300000,NaN,-159792,NaN,rebecca.carter@enron.com,NaN,NaN,15,29,7,...,75000,540,False,307301,-307301,261809,196,312,477557,NaN
BUCHANAN HAROLD G,500000,NaN,NaN,NaN,john.buchanan@enron.com,825464,600,125,0,0,...,304805,1215,False,189041,NaN,248017,23,1088,1054637,1014505
YEAP SOON,NaN,NaN,NaN,NaN,NaN,192758,55097,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,55097,192758
MURRAY JULIA H,400000,NaN,NaN,NaN,julia.murray@enron.com,400478,57580,45,11,2,...,125000,330,False,196983,NaN,229284,395,2192,812194,597461
GARLAND C KEVIN,850000,NaN,NaN,NaN,kevin.garland@enron.com,636246,48405,44,10,27,...,375304,60814,False,259907,NaN,231946,178,209,1566469,896153
DODSON KEITH,70000,NaN,NaN,NaN,keith.dodson@enron.com,NaN,28164,14,10,3,...,NaN,774,False,NaN,NaN,221003,114,176,319941,NaN
YEAGER F SCOTT,NaN,NaN,NaN,NaN,scott.yeager@enron.com,8308552,53947,NaN,NaN,NaN,...,NaN,147950,True,3576206,NaN,158403,NaN,NaN,360300,11884758
HIRKO JOSEPH,NaN,10259,NaN,NaN,joe.hirko@enron.com,30766064,77978,NaN,NaN,NaN,...,NaN,2856,True,NaN,NaN,NaN,NaN,NaN,91093,30766064
DIETRICH JANET R,600000,NaN,NaN,NaN,janet.dietrich@enron.com,1550019,3475,63,305,14,...,556416,473,False,315068,NaN,250100,1902,2572,1410464,1865087
DERRICK JR. JAMES V,800000,NaN,-1284000,NaN,james.derrick@enron.com,8831913,51124,909,64,20,...,484000,7482,False,1787380,-1787380,492375,1401,2181,550981,8831913
FREVERT MARK A,2000000,6426990,-3367011,NaN,mark.frevert@enron.com,10433518,86987,21,242,6,...,1617011,7427621,False,4188667,NaN,1060932,2979,3275,17252530,14622185
PAI LOU L,1000000,NaN,NaN,NaN,lou.pai@enron.com,15364167,32047,NaN,NaN,NaN,...,NaN,1829457,False,8453763,NaN,261879,NaN,NaN,3123383,23817930
HAYSLETT RODERICK J,NaN,NaN,NaN,NaN,rod.hayslett@enron.com,NaN,NaN,1061,35,38,...,NaN,NaN,False,346663,NaN,NaN,571,2649,NaN,346663
BAY FRANKLIN R,400000,260455,-201641,NaN,frank.bay@enron.com,NaN,129142,NaN,NaN,NaN,...,NaN,69,False,145796,-82782,239671,NaN,NaN,827696,63014
MCCARTY DANNY J,NaN,NaN,NaN,NaN,danny.mccarty@enron.com,664375,NaN,215,25,2,...,NaN,NaN,False,94556,NaN,NaN,508,1433,NaN,758931
FUGH JOHN L,NaN,50591,NaN,NaN,NaN,176378,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,50591,176378
SCRIMSHAW MATTHEW,NaN,NaN,NaN,NaN,matthew.scrimshaw@enron.com,759557,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,759557
KOENIG MARK E,700000,NaN,NaN,NaN,mark.koenig@enron.com,671737,127017,61,53,15,...,300000,150458,True,1248318,NaN,309946,2271,2374,1587421,1920055
SAVAGE FRANK,NaN,NaN,-121284,125034,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,3750,NaN
IZZO LAWRENCE L,NaN,NaN,NaN,NaN,larry.izzo@enron.com,2165172,28093,19,28,5,...,312500,1553729,False,3654808,NaN,85274,437,496,1979596,5819980
TILNEY ELIZABETH A,300000,NaN,-575000,NaN,elizabeth.tilney@enron.com,591250,NaN,19,10,11,...,275000,152055,False,576792,NaN,247338,379,460,399393,1168042
MARTIN AMANDA K,NaN,85430,NaN,NaN,a..martin@enron.com,2070306,8211,230,8,0,...,5145434,2818454,False,NaN,NaN,349487,477,1522,8407016,2070306
BUY RICHARD B,900000,649584,-694862,NaN,rick.buy@enron.com,2542813,NaN,1053,156,71,...,769862,400572,False,901657,NaN,330546,2333,3523,2355702,3444470
GRAMM WENDY L,NaN,NaN,NaN,119292,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,119292,NaN
CAUSEY RICHARD A,1000000,NaN,-235000,NaN,richard.causey@enron.com,NaN,30674,49,58,12,...,350000,307895,True,2502063,NaN,415189,1585,1892,1868758,2502063
TAYLOR MITCHELL S,600000,227449,NaN,NaN,mitchell.taylor@enron.com,3181250,NaN,29,0,0,...,NaN,NaN,False,563798,NaN,265214,300,533,1092663,3745048
DONAHUE JR JEFFREY M,800000,NaN,-300000,NaN,jeff.donahue@enron.com,765920,96268,22,188,11,...,NaN,891,False,315068,NaN,278601,772,865,875760,1080988
GLISAN JR BEN F,600000,NaN,NaN,NaN,ben.glisan@enron.com,384728,125978,16,52,6,...,71023,200308,True,393818,NaN,274975,874,873,1272284,778546

In [45]:
print(enron_data['LAY KENNETH L']['total_payments'])
print(enron_data['SKILLING JEFFREY K']['total_payments'])
print(enron_data['FASTOW ANDREW S']['total_payments'])

103559793
8682716
2424083

In [13]:

feature_format.featureFormat(enron_data,['total_payments','poi'])

array([[1.06182700e+06, 0.00000000e+00],
       [5.63434300e+06, 0.00000000e+00],
       [2.11725000e+05, 0.00000000e+00],
       [2.88682000e+05, 1.00000000e+00],
       [6.28522000e+05, 0.00000000e+00],
       [1.84822700e+06, 0.00000000e+00],
       [4.09977100e+06, 0.00000000e+00],
       [3.85906500e+06, 0.00000000e+00],
       [1.73762900e+06, 0.00000000e+00],
       [3.10022400e+06, 0.00000000e+00],
       [7.74401000e+05, 0.00000000e+00],
       [2.01483500e+06, 0.00000000e+00],
       [1.54505900e+06, 0.00000000e+00],
       [9.66522000e+05, 0.00000000e+00],
       [1.49034400e+06, 1.00000000e+00],
       [3.20207000e+06, 0.00000000e+00],
       [5.51174000e+05, 0.00000000e+00],
       [7.62135000e+05, 0.00000000e+00],
       [8.74100000e+04, 0.00000000e+00],
       [1.79878000e+06, 0.00000000e+00],
       [3.47114100e+06, 0.00000000e+00],
       [1.02500000e+05, 0.00000000e+00],
       [3.03870200e+06, 0.00000000e+00],
       [1.89583000e+05, 0.00000000e+00],
       [6.18850000e+05, 0.00000000e+00],
       [2.28656000e+05, 0.00000000e+00],
       [2.04759300e+06, 0.00000000e+00],
       [1.09910000e+06, 1.00000000e+00],
       [9.69068000e+05, 0.00000000e+00],
       [4.75000000e+02, 0.00000000e+00],
       [2.69232400e+06, 0.00000000e+00],
       [1.48000000e+02, 0.00000000e+00],
       [2.08179600e+06, 0.00000000e+00],
       [7.96100000e+03, 0.00000000e+00],
       [2.65261200e+06, 1.00000000e+00],
       [2.66422800e+06, 0.00000000e+00],
       [1.04257570e+07, 0.00000000e+00],
       [2.28474000e+05, 0.00000000e+00],
       [1.20458300e+06, 0.00000000e+00],
       [2.13071000e+05, 0.00000000e+00],
       [2.14697300e+06, 0.00000000e+00],
       [9.16197000e+05, 0.00000000e+00],
       [7.74920000e+04, 0.00000000e+00],
       [1.05754800e+06, 0.00000000e+00],
       [4.33538800e+06, 0.00000000e+00],
       [2.00388500e+06, 1.00000000e+00],
       [8.74920000e+04, 0.00000000e+00],
       [1.20864900e+06, 0.00000000e+00],
       [7.04896000e+05, 0.00000000e+00],
       [4.67757400e+06, 0.00000000e+00],
       [2.10136400e+06, 0.00000000e+00],
       [4.74797900e+06, 1.00000000e+00],
       [9.99356000e+05, 0.00000000e+00],
       [8.75889000e+05, 0.00000000e+00],
       [2.15100000e+03, 0.00000000e+00],
       [1.03559793e+08, 1.00000000e+00],
       [1.27158200e+06, 0.00000000e+00],
       [1.32155700e+06, 0.00000000e+00],
       [8.07956000e+05, 0.00000000e+00],
       [9.00585000e+05, 0.00000000e+00],
       [1.82466000e+05, 0.00000000e+00],
       [1.29746100e+06, 0.00000000e+00],
       [3.67634000e+06, 0.00000000e+00],
       [3.13186000e+06, 0.00000000e+00],
       [2.66958900e+06, 1.00000000e+00],
       [1.41485700e+06, 0.00000000e+00],
       [1.11529000e+05, 0.00000000e+00],
       [8.60136000e+05, 0.00000000e+00],
       [5.50163000e+06, 1.00000000e+00],
       [2.36815100e+06, 0.00000000e+00],
       [2.09326300e+06, 0.00000000e+00],
       [9.11453000e+05, 0.00000000e+00],
       [2.42408300e+06, 1.00000000e+00],
       [1.81755000e+05, 0.00000000e+00],
       [1.63929700e+06, 1.00000000e+00],
       [5.05050000e+05, 1.00000000e+00],
       [1.08682100e+06, 0.00000000e+00],
       [1.10139300e+06, 0.00000000e+00],
       [2.49787000e+05, 0.00000000e+00],
       [2.79420000e+04, 0.00000000e+00],
       [1.11208700e+06, 0.00000000e+00],
       [8.68271600e+06, 1.00000000e+00],
       [1.27900000e+03, 0.00000000e+00],
       [5.64348000e+05, 0.00000000e+00],
       [1.14665800e+06, 0.00000000e+00],
       [3.62096000e+05, 0.00000000e+00],
       [1.13046100e+06, 0.00000000e+00],
       [1.74752200e+06, 0.00000000e+00],
       [3.09886585e+08, 0.00000000e+00],
       [1.03439500e+06, 0.00000000e+00],
       [1.93435900e+06, 0.00000000e+00],
       [4.48444200e+06, 0.00000000e+00],
       [1.57651100e+06, 0.00000000e+00],
       [8.37500000e+04, 0.00000000e+00],
       [8.49920000e+04, 0.00000000e+00],
       [4.92880000e+04, 0.00000000e+00],
       [1.31876300e+06, 0.00000000e+00],
       [3.94475000e+05, 0.00000000e+00],
       [1.38669000e+06, 0.00000000e+00],
       [1.54562900e+07, 0.00000000e+00],
       [4.77557000e+05, 0.00000000e+00],
       [1.05463700e+06, 0.00000000e+00],
       [5.50970000e+04, 0.00000000e+00],
       [8.12194000e+05, 0.00000000e+00],
       [1.56646900e+06, 0.00000000e+00],
       [3.19941000e+05, 0.00000000e+00],
       [3.60300000e+05, 1.00000000e+00],
       [9.10930000e+04, 1.00000000e+00],
       [1.41046400e+06, 0.00000000e+00],
       [5.50981000e+05, 0.00000000e+00],
       [1.72525300e+07, 0.00000000e+00],
       [3.12338300e+06, 0.00000000e+00],
       [8.27696000e+05, 0.00000000e+00],
       [5.05910000e+04, 0.00000000e+00],
       [1.58742100e+06, 1.00000000e+00],
       [3.75000000e+03, 0.00000000e+00],
       [1.97959600e+06, 0.00000000e+00],
       [3.99393000e+05, 0.00000000e+00],
       [8.40701600e+06, 0.00000000e+00],
       [2.35570200e+06, 0.00000000e+00],
       [1.19292000e+05, 0.00000000e+00],
       [1.86875800e+06, 1.00000000e+00],
       [1.09266300e+06, 0.00000000e+00],
       [8.75760000e+05, 0.00000000e+00],
       [1.27228400e+06, 1.00000000e+00]])

In [46]:
sal=df[['total_payments','poi']]
sal.shape
# x=sal['poi']==True
sal[sal['total_payments']=='NaN'].shape

(21, 2)

In [53]:
sal[sal['poi']==True].shape

(18, 2)

In [33]:
aa=np.array(sal['total_payments'])

In [34]:
aa[aa=='NaN'].shape

(21,)

In [18]:
len(df[df['poi']==True])

18

In [22]:
names = pd.read_csv("../final_project/poi_names.txt")
len(names)

35

In [33]:
enron_data['PRENTICE JAMES']['total_stock_value']

1095040

In [31]:
enron_data['COLWELL WESLEY']

{'salary': 288542,
 'to_messages': 1758,
 'deferral_payments': 27610,
 'total_payments': 1490344,
 'loan_advances': 'NaN',
 'bonus': 1200000,
 'email_address': 'wes.colwell@enron.com',
 'restricted_stock_deferred': 'NaN',
 'deferred_income': -144062,
 'total_stock_value': 698242,
 'expenses': 16514,
 'from_poi_to_this_person': 240,
 'exercised_stock_options': 'NaN',
 'from_messages': 40,
 'other': 101740,
 'from_this_person_to_poi': 11,
 'poi': True,
 'long_term_incentive': 'NaN',
 'shared_receipt_with_poi': 1132,
 'restricted_stock': 698242,
 'director_fees': 'NaN'}

In [36]:
enron_data['Skilling Jeffrey K'.upper()]

{'salary': 1111258,
 'to_messages': 3627,
 'deferral_payments': 'NaN',
 'total_payments': 8682716,
 'loan_advances': 'NaN',
 'bonus': 5600000,
 'email_address': 'jeff.skilling@enron.com',
 'restricted_stock_deferred': 'NaN',
 'deferred_income': 'NaN',
 'total_stock_value': 26093672,
 'expenses': 29336,
 'from_poi_to_this_person': 88,
 'exercised_stock_options': 19250000,
 'from_messages': 108,
 'other': 22122,
 'from_this_person_to_poi': 30,
 'poi': True,
 'long_term_incentive': 1920000,
 'shared_receipt_with_poi': 2042,
 'restricted_stock': 6843672,
 'director_fees': 'NaN'}